### ISSUE TITLE
Change of use of \Manuscript

### ISSUE THREAD

**Issue by ahcvankampen** [EDS-Bioinformatics-Laboratory/ENCORE#26]
The \Manuscript directory is now meant for our publications related to the project.

I propose to extend its use to include e.g., reports from our internship students, literature reports from our students, project proposals,

What is then a better name for \Manuscript  --> ScholarlyOutputs

**Comment by pdmoerland** [comment]
I've always assumed that the proposed extended use was already covered by the original definition. Also the meaning of the word manuscript is fairly generic (https://en.wikipedia.org/wiki/Manuscript): "More recently, the term has come to be understood to further include any written, typed, or word-processed copy of an author's work, as distinguished from the rendition as a printed version of the same".

**Comment by ahcvankampen** [comment]
Improved content of 0_README.md in \Manuscript
