### ISSUE TITLE
Minor details

### ISSUE THREAD

**Issue by RdeBiotec** [EDS-Bioinformatics-Laboratory/ENCORE#5]
- In the STEP by STEP ENCORE guide v13, in 3.1.2.4, it says to check the instructions in 0_PROJECT.md to know how to change it. I think it would be good if the instructions explained how to deal with the .md format e.g. mentioning https://www.markdownguide.org/basic-syntax/
- The 00_README-FIRST.txt  has two "Notes:" instead of one.
- The 00_README-FIRST.txt  says that "The following files need to be updated by the project owner" but does not mention Navigation.conf nor Processing/0_SoftwareEnvironment/0_README.md nor ProjectDocumentation/LabJournal.txt nor Processing/0_README.md in that list. Perhaps "The following files and the files indicated in them need to be updated..." would solve it.

**Comment by ahcvankampen** [comment]
Considering the last point:
The 00_README-FIRST file concerns files that are in the root of the sFSS directory.
